# Production overrides.
#
# Usage (example):
#   docker compose --env-file env.prod --profile mongodb \
#     -f compose.yml -f compose.prod.yml up -d
#
# Intentionally minimal. Production should not publish internal service ports.
# Only localhost-bound ports are published, intended to be reverse-proxied by nginx.

services:
  core:
    ports:
      - '127.0.0.1:${ADMIN_HTTP_PORT:-3030}:3030'
      - '127.0.0.1:${ADMIN_SOCKET_PORT:-3031}:3031'

  router:
    ports:
      - '127.0.0.1:${CLIENT_HTTP_PORT:-3000}:3000'
      - '127.0.0.1:${CLIENT_SOCKET_PORT:-3001}:3001'

  ui:
    ports:
      - '127.0.0.1:${UI_PORT:-8080}:8080'

